services:
  naikkelas-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: ['pnpm', 'dev', '--host', '0.0.0.0', '--port', '3000']
    ports: [] # no host ports - proxying via nginx-proxy only
    networks:
      - nginx-net
