services:
  naikkelas-app:
    image: naikkelas:latest
    container_name: naikkelas-app
    restart: unless-stopped
    networks:
      - nginx-net
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - '3000' # internal only
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: naikkelas-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true

volumes:
  redis-data:
